version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -  # Install Node.js 12.x repository
      - apt-get install -y nodejs=12.14.0  # Install Node.js 12.14.0
  build:
    commands:
      - npm install  # Install project dependencies
      - npm test  # Run your tests (replace with your actual test command)
      - npm run build  # Build your Node.js project (replace with your actual build command)
      - zip -r my-project.zip ./  # Package the project into a zip file

artifacts:
  files: my-project.zip  # Specify the zip file to be uploaded
